name: Publish to APIM

on:
  workflow_dispatch:
    inputs:
      apiName:  # id of input
        description: 'repo name'
        required: true
        default: ''
      apiPolicyLink:
        description: ''
        required: true
        default: ''

jobs:
  publish-to-apim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish to APIM
        uses: kiransripada/azure-apim-actionn@main
        with:
          TENANT_ID: 445555-d9999-4900a-916123sd44
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SUBSCRIPTION_ID: 6664AAAb36e0-XXXX-YYY-ZZZ-a2z1233
          RESOURCE_GROUP_NAME: my-sandbox-apim-rg
          APIM_SERVICE_NAME: my-sandbox-apim
          APIM_API_NAME: mytwillio
          API_SPEC: https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_accounts_v1.json
          API_POLICY_LOCATION: ${{ inputs.apiPolicyLink }}
          AAD_ENDPOINT: https://login.microsoftonline.com/
          GRAPH_ENDPOINT: https://management.azure.com/
